const Actiontypes = {
  SET_PRODUCT: "SET_PRODUCT",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCTS: "REMOVE_SELECTED_PRODUCTS",
  ADD_CART: "ADD_CART,"
};
export default Actiontypes;
